package com.example.todoapp;

import com.example.todoapp.dataModel.ToDoData;
import com.example.todoapp.dataModel.ToDoItem;
import javafx.beans.value.ChangeListener;
import javafx.beans.value.ObservableValue;
import javafx.fxml.FXML;
import javafx.scene.control.Label;
import javafx.scene.control.ListView;
import javafx.scene.control.SelectionMode;
import javafx.scene.control.TextArea;

import java.time.LocalDate;
import java.time.Month;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

public class Controller {
    private List<ToDoItem> ToDoItems = new ArrayList<ToDoItem>();
    @FXML
    private ListView todoListView;
    @FXML
    private TextArea itemDetailsTextArea;
    @FXML
    private Label deadLineLable;
    // Initialize with sample data
    public void initialize()
    {
//        todoItem item1 = new todoItem("Buy Birthday Card","Buy a birthday card for the manager",LocalDateTime.now() );
        ToDoItem item1 = new ToDoItem("Buy Birthday Card","India, officially the Republic of India (Hindi: Bhārat Gaṇarājya),[25] is a country in South Asia. It is the seventh-largest country by area, the second-most populous country, and the most populous democracy in the world. Bounded by the Indian Ocean on the south, the Arabian Sea on the southwest, and the Bay of Bengal on the southeast, it shares land borders with Pakistan to the west;[f] China, Nepal, and Bhutan to the north; and Bangladesh and Myanmar to the east. In the Indian Ocean, India is in the vicinity of Sri Lanka and the Maldives; its Andaman and Nicobar Islands share a maritime border with Thailand, Myanmar, and Indonesia.\n" +
                "\n" +
                "Modern humans arrived on the Indian subcontinent from Africa no later than 55,000 years ago.[26][27][28] Their long occupation, initially in varying forms of isolation as hunter-gatherers, has made the region highly diverse, second only to Africa in human genetic diversity.[29] Settled life emerged on the subcontinent in the western margins of the Indus river basin 9,000 years ago, evolving gradually into the Indus Valley Civilisation of the third millennium BCE.[30] By 1200 BCE, an archaic form of Sanskrit, an Indo-European language, had diffused into India from the northwest.[31][32] Its evidence today is found in the hymns of the Rigveda. Preserved by a resolutely vigilant oral tradition, the Rigveda records the dawning of Hinduism in India.[33] The Dravidian languages of India were supplanted in the northern and western regions.[34] By 400 BCE, stratification and exclusion by caste had emerged within Hinduism,[35] and Buddhism and Jainism had arisen, proclaiming social orders unlinked to heredity.[36] Early political consolidations gave rise to the loose-knit Maurya and Gupta Empires based in the Ganges Basin.[37] Their collective era was suffused with wide-ranging creativity,[38] but also marked by the declining status of women,[39] and the incorporation of untouchability into an organised system of belief.[g][40] In South India, the Middle kingdoms exported Dravidian-languages scripts and religious cultures to the kingdoms of Southeast Asia.[41]\n" +
                "\n" +
                "In the early medieval era, Christianity, Islam, Judaism, and Zoroastrianism became established on India's southern and western coasts.[42] Muslim armies from Central Asia intermittently overran India's northern plains,[43] eventually founding the Delhi Sultanate, and drawing northern India into the cosmopolitan networks of medieval Islam.[44] In the 15th century, the Vijayanagara Empire created a long-lasting composite Hindu culture in south India.[45] In the Punjab, Sikhism emerged, rejecting institutionalised religion.[46] The Mughal Empire, in 1526, ushered in two centuries of relative peace,[47] leaving a legacy of luminous architecture.[h][48] Gradually expanding rule of the British East India Company followed, turning India into a colonial economy, but also consolidating its sovereignty.[49] British Crown rule began in 1858. The rights promised to Indians were granted slowly,[50][51] but technological changes were introduced, and modern ideas of education and the public life took root.[52] A pioneering and influential nationalist movement led by Mahatma Gandhi emerged, which was noted for nonviolent resistance and it became the major factor in ending British rule.[53][54] In 1947 the British Indian Empire was partitioned into two independent dominions,[55][56][57][58] a Hindu-majority Dominion of India and a Muslim-majority Dominion of Pakistan, amid large-scale loss of life and an unprecedented migration.[59]\n" +
                "\n" +
                "India has been a federal republic since 1950, governed through a democratic parliamentary system. It is a pluralistic, multilingual and multi-ethnic society. India's population grew from 361 million in 1951 to almost 1.4 billion in 2022.[60] During the same time, its nominal per capita income increased from US$64 annually to US$1,498, and its literacy rate from 16.6% to 74%. From being a comparatively destitute country in 1951,[61] India has become a fast-growing major economy and a hub for information technology services, with an expanding middle class.[62] It has a space programme which includes several planned or completed extraterrestrial missions. Indian movies, music, and spiritual teachings play an increasing role in global culture.[63] India has substantially reduced its rate of poverty, though at the cost of increasing economic inequality.[64] India is a nuclear-weapon state, which ranks high in military expenditure. It has disputes over Kashmir with its neighbours, Pakistan and China, unresolved since the mid-20th century.[65] Among the socio-economic challenges India faces are gender inequality, child malnutrition,[66] and rising levels of air pollution.[67] India's land is megadiverse, with four biodiversity hotspots.[68] Its forest cover comprises 21.7% of its area.[69] India's wildlife, which has traditionally been viewed with tolerance in India's culture,[70] is supported among these forests, and elsewhere, in protected habitats.\n" +
                "\n" +
                "Etymology\n" +
                "According to the Oxford English Dictionary (third edition 2009), the name \"India\" is derived from the Classical Latin India, a reference to South Asia and an uncertain region to its east; and in turn derived successively from: Hellenistic Greek India ( Ἰνδία); ancient Greek Indos ( Ἰνδός); Old Persian Hindush, an eastern province of the Achaemenid Empire; and ultimately its cognate, the Sanskrit Sindhu, or \"river,\" specifically the Indus River and, by implication, its well-settled southern basin.[71][72] The ancient Greeks referred to the Indians as Indoi (Ἰνδοί), which translates as \"The people of the Indus\".[73]\n" +
                "\n" +
                "The term Bharat (Bhārat; pronounced [ˈbʱaːɾət] (listen)), mentioned in both Indian epic poetry and the Constitution of India,[74][75] is used in its variations by many Indian languages. A modern rendering of the historical name Bharatavarsha, which applied originally to North India,[76][77] Bharat gained increased currency from the mid-19th century as a native name for India.[74][78]\n" +
                "\n" +
                "Hindustan ([ɦɪndʊˈstaːn] (listen)) is a Middle Persian name for India, introduced during the Mughal Empire and used widely since. Its meaning has varied, referring to a region encompassing present-day northern India and Pakistan or to India in its near entirety.[74][78][79]", LocalDate.of(2023, Month.FEBRUARY,21));
        ToDoItem item2 = new ToDoItem("Meeting with Paul","By 55,000 years ago, the first modern humans, or Homo sapiens, had arrived on the Indian subcontinent from Africa, where they had earlier evolved.[26][27][28] The earliest known modern human remains in South Asia date to about 30,000 years ago.[26] After 6500 BCE, evidence for domestication of food crops and animals, construction of permanent structures, and storage of agricultural surplus appeared in Mehrgarh and other sites in what is now Balochistan, Pakistan.[81] These gradually developed into the Indus Valley Civilisation,[82][81] the first urban culture in South Asia,[83] which flourished during 2500–1900 BCE in what is now Pakistan and western India.[84] Centred around cities such as Mohenjo-daro, Harappa, Dholavira, and Kalibangan, and relying on varied forms of subsistence, the civilisation engaged robustly in crafts production and wide-ranging trade.[83]\n" +
                "\n" +
                "During the period 2000–500 BCE, many regions of the subcontinent transitioned from the Chalcolithic cultures to the Iron Age ones.[85] The Vedas, the oldest scriptures associated with Hinduism,[86] were composed during this period,[87] and historians have analysed these to posit a Vedic culture in the Punjab region and the upper Gangetic Plain.[85] Most historians also consider this period to have encompassed several waves of Indo-Aryan migration into the subcontinent from the north-west.[86] The caste system, which created a hierarchy of priests, warriors, and free peasants, but which excluded indigenous peoples by labelling their occupations impure, arose during this period.[88] On the Deccan Plateau, archaeological evidence from this period suggests the existence of a chiefdom stage of political organisation.[85] In South India, a progression to sedentary life is indicated by the large number of megalithic monuments dating from this period,[89] as well as by nearby traces of agriculture, irrigation tanks, and craft traditions.[89]\n" +
                "\n" +
                "\n" +
                "Cave 26 of the rock-cut Ajanta Caves\n" +
                "In the late Vedic period, around the 6th century BCE, the small states and chiefdoms of the Ganges Plain and the north-western regions had consolidated into 16 major oligarchies and monarchies that were known as the mahajanapadas.[90][91] The emerging urbanisation gave rise to non-Vedic religious movements, two of which became independent religions. Jainism came into prominence during the life of its exemplar, Mahavira.[92] Buddhism, based on the teachings of Gautama Buddha, attracted followers from all social classes excepting the middle class; chronicling the life of the Buddha was central to the beginnings of recorded history in India.[93][94][95] In an age of increasing urban wealth, both religions held up renunciation as an ideal,[96] and both established long-lasting monastic traditions. Politically, by the 3rd century BCE, the kingdom of Magadha had annexed or reduced other states to emerge as the Mauryan Empire.[97] The empire was once thought to have controlled most of the subcontinent except the far south, but its core regions are now thought to have been separated by large autonomous areas.[98][99] The Mauryan kings are known as much for their empire-building and determined management of public life as for Ashoka's renunciation of militarism and far-flung advocacy of the Buddhist dhamma.[100][101]\n" +
                "\n" +
                "The Sangam literature of the Tamil language reveals that, between 200 BCE and 200 CE, the southern peninsula was ruled by the Cheras, the Cholas, and the Pandyas, dynasties that traded extensively with the Roman Empire and with West and Southeast Asia.[102][103] In North India, Hinduism asserted patriarchal control within the family, leading to increased subordination of women.[104][97] By the 4th and 5th centuries, the Gupta Empire had created a complex system of administration and taxation in the greater Ganges Plain; this system became a model for later Indian kingdoms.[105][106] Under the Guptas, a renewed Hinduism based on devotion, rather than the management of ritual, began to assert itself.[107] This renewal was reflected in a flowering of sculpture and architecture, which found patrons among an urban elite.[106] Classical Sanskrit literature flowered as well, and Indian science, astronomy, medicine, and mathematics made significant advances.[106]", LocalDate.of(2023, Month.JULY,01));
        ToDoItem item3 = new ToDoItem("Go to Mall","he Indian early medieval age, from 600 to 1200 CE, is defined by regional kingdoms and cultural diversity.[108] When Harsha of Kannauj, who ruled much of the Indo-Gangetic Plain from 606 to 647 CE, attempted to expand southwards, he was defeated by the Chalukya ruler of the Deccan.[109] When his successor attempted to expand eastwards, he was defeated by the Pala king of Bengal.[109] When the Chalukyas attempted to expand southwards, they were defeated by the Pallavas from farther south, who in turn were opposed by the Pandyas and the Cholas from still farther south.[109] No ruler of this period was able to create an empire and consistently control lands much beyond their core region.[108] During this time, pastoral peoples, whose land had been cleared to make way for the growing agricultural economy, were accommodated within caste society, as were new non-traditional ruling classes.[110] The caste system consequently began to show regional differences.[110]\n" +
                "\n" +
                "In the 6th and 7th centuries, the first devotional hymns were created in the Tamil language.[111] They were imitated all over India and led to both the resurgence of Hinduism and the development of all modern languages of the subcontinent.[111] Indian royalty, big and small, and the temples they patronised drew citizens in great numbers to the capital cities, which became economic hubs as well.[112] Temple towns of various sizes began to appear everywhere as India underwent another urbanisation.[112] By the 8th and 9th centuries, the effects were felt in South-East Asia, as South Indian culture and political systems were exported to lands that became part of modern-day Myanmar, Thailand, Laos, Brunei, Cambodia, Vietnam, Philippines, Malaysia, and Indonesia.[113] Indian merchants, scholars, and sometimes armies were involved in this transmission; South-East Asians took the initiative as well, with many sojourning in Indian seminaries and translating Buddhist and Hindu texts into their languages.[113]\n" +
                "\n" +
                "After the 10th century, Muslim Central Asian nomadic clans, using swift-horse cavalry and raising vast armies united by ethnicity and religion, repeatedly overran South Asia's north-western plains, leading eventually to the establishment of the Islamic Delhi Sultanate in 1206.[114] The sultanate was to control much of North India and to make many forays into South India. Although at first disruptive for the Indian elites, the sultanate largely left its vast non-Muslim subject population to its own laws and customs.[115][116] By repeatedly repulsing Mongol raiders in the 13th century, the sultanate saved India from the devastation visited on West and Central Asia, setting the scene for centuries of migration of fleeing soldiers, learned men, mystics, traders, artists, and artisans from that region into the subcontinent, thereby creating a syncretic Indo-Islamic culture in the north.[117][118] The sultanate's raiding and weakening of the regional kingdoms of South India paved the way for the indigenous Vijayanagara Empire.[119] Embracing a strong Shaivite tradition and building upon the military technology of the sultanate, the empire came to control much of peninsular India,[120] and was to influence South Indian society for long afterwards.[119]", LocalDate.of(2023, Month.MARCH,11));
        ToDoItem item4 = new ToDoItem("Get license activated","In the early 16th century, northern India, then under mainly Muslim rulers,[121] fell again to the superior mobility and firepower of a new generation of Central Asian warriors.[122] The resulting Mughal Empire did not stamp out the local societies it came to rule. Instead, it balanced and pacified them through new administrative practices[123][124] and diverse and inclusive ruling elites,[125] leading to more systematic, centralised, and uniform rule.[126] Eschewing tribal bonds and Islamic identity, especially under Akbar, the Mughals united their far-flung realms through loyalty, expressed through a Persianised culture, to an emperor who had near-divine status.[125] The Mughal state's economic policies, deriving most revenues from agriculture[127] and mandating that taxes be paid in the well-regulated silver currency,[128] caused peasants and artisans to enter larger markets.[126] The relative peace maintained by the empire during much of the 17th century was a factor in India's economic expansion,[126] resulting in greater patronage of painting, literary forms, textiles, and architecture.[129] Newly coherent social groups in northern and western India, such as the Marathas, the Rajputs, and the Sikhs, gained military and governing ambitions during Mughal rule, which, through collaboration or adversity, gave them both recognition and military experience.[130] Expanding commerce during Mughal rule gave rise to new Indian commercial and political elites along the coasts of southern and eastern India.[130] As the empire disintegrated, many among these elites were able to seek and control their own affairs.[131]\n" +
                "\n" +
                "\n" +
                "A distant view of the Taj Mahal from the Agra Fort\n" +
                "\n" +
                "A two mohur Company gold coin, issued in 1835, the obverse inscribed \"William IV, King\"\n" +
                "By the early 18th century, with the lines between commercial and political dominance being increasingly blurred, a number of European trading companies, including the English East India Company, had established coastal outposts.[132][133] The East India Company's control of the seas, greater resources, and more advanced military training and technology led it to increasingly assert its military strength and caused it to become attractive to a portion of the Indian elite; these factors were crucial in allowing the company to gain control over the Bengal region by 1765 and sideline the other European companies.[134][132][135][136] Its further access to the riches of Bengal and the subsequent increased strength and size of its army enabled it to annexe or subdue most of India by the 1820s.[137] India was then no longer exporting manufactured goods as it long had, but was instead supplying the British Empire with raw materials. Many historians consider this to be the onset of India's colonial period.[132] By this time, with its economic power severely curtailed by the British parliament and having effectively been made an arm of British administration, the East India Company began more consciously to enter non-economic arenas, including education, social reform and culture.[138]", LocalDate.of(2023, Month.APRIL,30));
        ToDoItem item5 = new ToDoItem("get system updated","Historians consider India's modern age to have begun sometime between 1848 and 1885. The appointment in 1848 of Lord Dalhousie as Governor General of the East India Company set the stage for changes essential to a modern state. These included the consolidation and demarcation of sovereignty, the surveillance of the population, and the education of citizens. Technological changes—among them, railways, canals, and the telegraph—were introduced not long after their introduction in Europe.[139][140][141][142] However, disaffection with the company also grew during this time and set off the Indian Rebellion of 1857. Fed by diverse resentments and perceptions, including invasive British-style social reforms, harsh land taxes, and summary treatment of some rich landowners and princes, the rebellion rocked many regions of northern and central India and shook the foundations of Company rule.[143][144] Although the rebellion was suppressed by 1858, it led to the dissolution of the East India Company and the direct administration of India by the British government. Proclaiming a unitary state and a gradual but limited British-style parliamentary system, the new rulers also protected princes and landed gentry as a feudal safeguard against future unrest.[145][146] In the decades following, public life gradually emerged all over India, leading eventually to the founding of the Indian National Congress in 1885.[147][148][149][150]\n" +
                "\n" +
                "The rush of technology and the commercialisation of agriculture in the second half of the 19th century was marked by economic setbacks and many small farmers became dependent on the whims of far-away markets.[151] There was an increase in the number of large-scale famines,[152] and, despite the risks of infrastructure development borne by Indian taxpayers, little industrial employment was generated for Indians.[153] There were also salutary effects: commercial cropping, especially in the newly canalled Punjab, led to increased food production for internal consumption.[154] The railway network provided critical famine relief,[155] notably reduced the cost of moving goods,[155] and helped nascent Indian-owned industry.[154]\n" +
                "\n" +
                "\n" +
                "1909 map of the British Indian Empire\n" +
                "\n" +
                "Jawaharlal Nehru sharing a light moment with Mahatma Gandhi, Mumbai, 6 July 1946\n" +
                "After World War I, in which approximately one million Indians served,[156] a new period began. It was marked by British reforms but also repressive legislation, by more strident Indian calls for self-rule, and by the beginnings of a nonviolent movement of non-co-operation, of which Mahatma Gandhi would become the leader and enduring symbol.[157] During the 1930s, slow legislative reform was enacted by the British; the Indian National Congress won victories in the resulting elections.[158] The next decade was beset with crises: Indian participation in World War II, the Congress's final push for non-co-operation, and an upsurge of Muslim nationalism. All were capped by the advent of independence in 1947, but tempered by the partition of India into two states: India and Pakistan.[159]\n" +
                "\n" +
                "Vital to India's self-image as an independent nation was its constitution, completed in 1950, which put in place a secular and democratic republic.[160] Per the London Declaration, India retained its membership of the Commonwealth, becoming the first republic within it.[161] Economic liberalisation, which began in the 1990s, has created a large urban middle class, transformed India into one of the world's fastest-growing economies,[162] and increased its geopolitical clout. Indian films, music, and spiritual teachings play an increasing role in global culture.[163] Yet, India is also shaped by seemingly unyielding poverty, both rural and urban;[163] by religious and caste-related violence;[164] by Maoist-inspired Naxalite insurgencies;[165] and by separatism in Jammu and Kashmir and in Northeast India.[166] It has unresolved territorial disputes with China[167] and with Pakistan.[167] India's sustained democratic freedoms are unique among the world's newer nations; however, in spite of its recent economic successes, freedom from want for its disadvantaged population remains a goal yet to be achieved.[168]", LocalDate.of(2023, Month.JUNE,15));
        ToDoItems.add(item1);
        ToDoItems.add(item2);
        ToDoItems.add(item3);
        ToDoItems.add(item4);
        ToDoItems.add(item5);
        ToDoData.getInstance().setToDoItems(ToDoItems);
        todoListView.getSelectionModel().selectedItemProperty().addListener(new ChangeListener<ToDoItem>() {
            @Override
            public void changed(ObservableValue<? extends ToDoItem> observableValue, ToDoItem oldValue, ToDoItem newValue) {
                if(newValue !=null)
                {
                    ToDoItem item = (ToDoItem) todoListView.getSelectionModel().getSelectedItem();
                    itemDetailsTextArea.setText(item.getDetails());
                    DateTimeFormatter df = DateTimeFormatter.ofPattern("MMMM d, yyyy");
                    deadLineLable.setText(df.format(item.getDeadLine()));

                }
            }
        });
        todoListView.getItems().setAll(ToDoItems);
        todoListView.getSelectionModel().setSelectionMode(SelectionMode.SINGLE);
        todoListView.getSelectionModel().selectFirst();
    }
    @FXML
    public void handleClickListView()
    {
        ToDoItem item = (ToDoItem) todoListView.getSelectionModel().getSelectedItem();
        itemDetailsTextArea.setText(item.getDetails());
        deadLineLable.setText(item.getDeadLine().toString());
//        System.out.println("The selected Item is: "+item);
//        StringBuilder sb = new StringBuilder(item.getDetails());
//        sb.append("\n\n\n\n");
//        sb.append("Due Date: ").append(item.getDeadLine().toString());
//        itemDetailsTextArea.setText(sb.toString());
    }
}
